version: "3"
services:
  windows_node:
    build:
      context: .
      dockerfile: Dockerfile.windev
    ports:
      - "25985:5985"
      - "25986:5986"
    networks:
      test_net:
        ipv4_address: 172.28.1.1

  windows_agent:
    build:
      context: .
      dockerfile: Dockerfile.winagent
    ports:
      - "35985:5985"
      - "35986:5986"
    networks:
      test_net:
        ipv4_address: 172.28.1.2

networks:
  test_net:
    external:
      name: spec_default
