name: LXD

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', '**.erb', 'schemas/*']
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths-ignore: ['**.md', '**.erb', 'schemas/*']

jobs:
  lxd:
    name: LXD
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.7, 3.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Add user to LXD group
        run: sudo usermod -aG lxd `whoami`
      - name: LXD Init
        run: sg lxd -c "cat spec/lxd_config.yaml | lxd init --preseed"
      - name: Launch container
        run: sg lxd -c "lxc launch ubuntu:focal testlxd"
      - name: Install Puppetfile
        run: bundle exec r10k puppetfile install
      - name: Run tests with minimal container infrastructure
        run: sg lxd -c "bundle exec rake tests:lxd"
