name: Trigger Powershell cmdlets module update

on:
  push:
    branches: [master]
    paths: ['pwsh/*']

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: lucywyman/bolt-vanagon
          event-type: update-cmdlets
          client-payload: '{"sha": "${{ github.sha }}"}'
